vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
vim.opt.smarttab = true
vim.opt.smartindent = true
vim.opt.hlsearch = false
vim.opt.wrap = false
vim.opt.hidden = true
vim.opt.incsearch = true
vim.opt.scrolloff = 8
vim.opt.laststatus = 2
vim.opt.signcolumn = "yes"
vim.opt.colorcolumn = "80"
vim.opt.updatetime = 50
vim.opt.clipboard = "unnamed"
vim.opt.swapfile = false

vim.g.mapleader = " "
